CFLAGS= -Wall -Werror -pedantic -std=c99 -O2
CC= gcc

problem96: problem96.o

problem96.o: problem96.c

edit:
	vim problem96.c
clean:
	rm -f problem96 problem96.o

run:
	./problem96

.PHONY: clean run edit

